/*
SET  A=(SELECT *
       FROM EMPLOYEES
       WHERE SALARY >10000)

SET  B=(SELECT *
       FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 100;)
*/


-- UNION SUDU COMMON-UNCOMMON GULA AND AK JINIS 2BAR THAKLE AKBR NIBE
SELECT *
FROM EMPLOYEES
WHERE SALARY >10000
UNION 
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;


-- UNION ALL SUDU COMMON-UNCOMMON GULA AND AK JINIS 2BAR THAKLE 2BAR E NIBE
SELECT *
FROM EMPLOYEES
WHERE SALARY >10000
UNION ALL
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;


-- INTERSECT SUDU COMMON  GULA NIBE
SELECT *
FROM EMPLOYEES
WHERE SALARY >10000
INTERSECT
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- MINUS SET AIVABE MENUALLY KORTE HOY ,,MANE COMMONDA BADE NIBE 
SELECT *
FROM EMPLOYEES
WHERE SALARY >10000 AND DEPARTMENT_ID != 100;

