
SELECT FIRST_NAME,UPPER(FIRST_NAME)
FROM EMPLOYEES;

SELECT LOWER(FIRST_NAME)
FROM EMPLOYEES;

SELECT COS(RADIANS(90)); -- cos er man ber korar jonno and seita age redians kore nite hoy

SELECT PI();

SELECT ROUND(3.567,2); -- Dosomic er por koy ghor rakbo er jonno

SELECT RAND(); -- Randomly akta songkhar jonno

SELECT GREATEST(10,2,16,20,78); -- MAX NUMBER ER JONNO

SELECT LEAST(10,2,16,20,78); -- MIN NUMBER ER JONNO

SELECT CEIL(20.6) , FLOOR(20.6) -- CEIL MINIMUM AND FLOOR MAXIMUM ER JONNO


-- Group Function

SELECT MAX(salary)
FROM EMPLOYEES;

SELECT MIN(salary)
FROM EMPLOYEES;

SELECT SUM(salary)
FROM EMPLOYEES;

SELECT AVG(salary)
FROM EMPLOYEES;

SELECT COUNT(salary) -- KOTO  JONER SALARY ACE SEITA DEKHABE
FROM EMPLOYEES ;

SELECT COUNT(employee_ID) -- KOTO  JONE EMPLOYEES ACE SEITA DEKHABE
FROM EMPLOYEES ;

SELECT COUNT(manager_id) -- KOTO  JONER MANAGER_ID ACE SEITA DEKHABE
FROM EMPLOYEES ;

SELECT COUNT(*) -- KOYTA ROW ACE 
FROM EMPLOYEES;

-- GROUP BY
SELECT DEPARTMENT_ID, MIN(salary) -- PROTITA DEPARTMENTI_ID ER MINIMUM SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(salary) -- PROTITA DEPARTMENTI_ID ER AVARAGE SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*) -- PROTITA DEPARTMENTI A KOTOJON ACE
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- HAVING ER BOISISTHO 
SELECT DEPARTMENT_ID, MAX(salary) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID != 20  -- TABLE ER JONNO CONDITION
GROUP BY DEPARTMENT_ID
HAVING MAX(salary) >5000; -- GROUP FUNTION ER JONNO CONDITION