--  Joining Tables without using JOIN Query
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- Joining Tables with JOIN Query
SELECT FIRST_NAME,DEPARTMENT_NAME,EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES 
     JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

--  INNER, LEFT, RIGHT, CROSS Join

--  INNER JOIN QUERY,,SDAHARON JOIN AND INNER JOIN SAME
SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES
    INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- LEFT JOIN QUERY,, BUJAR JONNO EMPLOYYE_ID ER SATHE DEPARTMENT_ID ER SORTHO USE KORCHI
SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES
    LEFT JOIN DEPARTMENTS ON EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID;

    --EXAMPLE ,,JE SOKOL DEPARTMENT A EMPLOYEE NEI SEI DEPARTMENT NAME USE LEFT JOIN
    SELECT DEPARTMENTS.DEPARTMENT_NAME
    FROM DEPARTMENTS
         LEFT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
    WHERE EMPLOYEES.DEPARTMENT_ID IS NULL

-- RIGHT JOIN QUERY,, BUJAR JONNO EMPLOYYE_ID ER SATHE DEPARTMENT_ID ER SORTHO USE KORCHI
SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES
    RIGHT JOIN DEPARTMENTS ON EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID;

-- CROSS JOIN QUERY,, BUJAR JONNO EMPLOYYE_ID ER SATHE DEPARTMENT_ID ER SORTHO USE KORCHI
SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES
    CROSS JOIN DEPARTMENTS ON EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID;


-- SELF JOIN QUERY
SELECT M.FIRST_NAME AS EMPLOYEE_NAME,E.FIRST_NAME AS MANAGER_NAME
FROM EMPLOYEES AS E
     JOIN EMPLOYEES AS M
     ON M.MANAGER_ID= E.EMPLOYEE_ID ; 
